# Base configuration for the training pipeline
# Users can copy this file and adjust values as needed.
dataset: breast_cancer
test_size: 0.2
random_state: 42
model_type: logistic_regression
logistic_regression:
  C: 2.5
  max_iter: 500
  penalty: l2
random_forest:
  n_estimators: 300
  max_depth: null
  min_samples_split: 5
output_dir: artifacts
